DROP TABLE IF EXISTS author CASCADE;
DROP TABLE IF EXISTS interviewee CASCADE;
DROP TABLE IF EXISTS questionnaire CASCADE;
DROP TABLE IF EXISTS option CASCADE;
DROP TABLE IF EXISTS choice CASCADE;
DROP TABLE IF EXISTS option_choice CASCADE;
DROP TABLE IF EXISTS country CASCADE;