DROP TABLE IF EXISTS answered CASCADE;
DROP TABLE IF EXISTS choice CASCADE;
DROP TABLE IF EXISTS option CASCADE;
DROP TABLE IF EXISTS questionnaire CASCADE;
DROP TABLE IF EXISTS user_table CASCADE;
DROP TABLE IF EXISTS country CASCADE;